# Generated by Django 2.1 on 2019-01-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerprofile',
            name='trainer_key',
            field=models.CharField(default='xa801eab4', max_length=100),
        ),
    ]
