# Generated by Django 2.1 on 2019-01-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='paystack_plan_id',
            field=models.CharField(default='0xdf84cfee', max_length=50),
        ),
        migrations.AlterField(
            model_name='paystackpayment',
            name='user_key',
            field=models.CharField(default='0xdf04674e', max_length=200),
        ),
    ]
